package domain

import "errors"

var (
	ErrProfileNotFound      = errors.New("handler profile not found")
	ErrProfileRequired      = errors.New("handler profile required")
	ErrProfileAccessDenied  = errors.New("handler profile access denied")
	ErrDisplayNameRequired  = errors.New("display name is required")
	ErrDisplayNameTooLong   = errors.New("display name is too long")
	ErrBioTooLong           = errors.New("bio is too long")
	ErrConditionsTooLong    = errors.New("conditions are too long")
	ErrInvalidExperience    = errors.New("invalid experience years")
	ErrServiceNotFound      = errors.New("handler service not found")
	ErrServiceAccessDenied  = errors.New("handler service access denied")
	ErrInvalidServiceType   = errors.New("invalid service type")
	ErrServiceTitleRequired = errors.New("service title is required")
	ErrServiceTitleTooLong  = errors.New("service title is too long")
	ErrDescriptionTooLong   = errors.New("description is too long")
	ErrInvalidPrice         = errors.New("invalid price")
	ErrInvalidDuration      = errors.New("invalid duration")
	ErrRequestNotFound      = errors.New("service request not found")
	ErrRequestAccessDenied  = errors.New("service request access denied")
	ErrPetAccessDenied      = errors.New("pet access denied")
	ErrInactiveHandler      = errors.New("handler is not accepting requests")
	ErrInactiveService      = errors.New("service is not active")
	ErrSelfRequest          = errors.New("cannot request own service")
	ErrInvalidRequestDate   = errors.New("invalid request date")
	ErrInvalidRequestTime   = errors.New("invalid request time")
	ErrInvalidRequestStatus = errors.New("invalid request status")
	ErrInvalidStatusChange  = errors.New("invalid status change")
	ErrReviewNotAllowed     = errors.New("review is allowed only for completed request")
	ErrReviewAlreadyExists  = errors.New("review already exists")
	ErrInvalidRating        = errors.New("invalid rating")
	ErrReviewBodyTooLong    = errors.New("review body is too long")
)
